name: blue_ocean_field
dependencies:
  - python=3.12
  - numpy
  - sqlalchemy
  - aiosqlite
  - rx
  - pytest
  - pytest-cov
  - pytest-asyncio
  - ta-lib
  - injector
  - isort
  - configparser
  - grpcio
  - grpcio-tools
  - grpcio-reflection
  - protobuf
  - cython
  - rust
  - pip
  - pip:
    - ccxt==4.4.1
    - "git+https://github.com/online-ml/river"
